src/Entity/Evenements.php
<?php

namespace App\Entity;

use App\Repository\EvenementsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementsRepository::class)
 */
class Evenements
{

// ====================================================== //
// ===================== PROPRIETES ===================== //
// ====================================================== //

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $illustration;

    /**
     * @ORM\ManyToOne(targetEntity=TypeEvenement::class, inversedBy="evenements")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sousTitre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\ManyToOne(targetEntity=Galerie::class, inversedBy="evenements")
     */
    private $galerie;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $actif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Horaire;

// ====================================================== //
// =================== GETTER /SETTER =================== //
// ====================================================== //

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(?string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getType(): ?TypeEvenement
    {
        return $this->type;
    }

    public function setType(?TypeEvenement $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getSousTitre(): ?string
    {
        return $this->sousTitre;
    }

    public function setSousTitre(?string $sousTitre): self
    {
        $this->sousTitre = $sousTitre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getGalerie(): ?Galerie
    {
        return $this->galerie;
    }

    public function setGalerie(?Galerie $galerie): self
    {
        $this->galerie = $galerie;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(?bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getHoraire(): ?string
    {
        return $this->Horaire;
    }

    public function setHoraire(string $Horaire): self
    {
        $this->Horaire = $Horaire;

        return $this;
    }
}

src/Controller/AdminMediaController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Form\MediaType;
use App\Repository\MediaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/media")
 */
class AdminMediaController extends AbstractController
{
    /**
     * @Route("/", name="app_admin_media_index", methods={"GET"})
     */
    public function index(MediaRepository $mediaRepository): Response
    {
        return $this->render('admin_media/index.html.twig', [
            'media' => $mediaRepository->findAll(),
            'active' => 'adm-medias',
        ]);
    }

    /**
     * @Route("/new", name="app_admin_media_new", methods={"GET", "POST"})
     */
    public function new(Request $request, MediaRepository $mediaRepository): Response
    {
        $medium = new Media();
        $form = $this->createForm(MediaType::class, $medium);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mediaRepository->add($medium, true);

            return $this->redirectToRoute('app_admin_media_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_media/new.html.twig', [
            'medium' => $medium,
            'form' => $form,
            'active' => 'adm-medias',
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_media_show", methods={"GET"})
     */
    public function show(Media $medium): Response
    {
        return $this->render('admin_media/show.html.twig', [
            'medium' => $medium,
            'active' => 'adm-medias',
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_admin_media_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Media $medium, MediaRepository $mediaRepository): Response
    {
        $form = $this->createForm(MediaType::class, $medium);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mediaRepository->add($medium, true);

            return $this->redirectToRoute('app_admin_media_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_media/edit.html.twig', [
            'medium' => $medium,
            'form' => $form,
            'active' => 'adm-medias',
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_media_delete", methods={"POST"})
     */
    public function delete(Request $request, Media $medium, MediaRepository $mediaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medium->getId(), $request->request->get('_token'))) {
            $mediaRepository->remove($medium, true);
        }

        return $this->redirectToRoute('app_admin_media_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_media/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_media_delete', {'id': medium.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medium.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_media/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_media/edit.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Editer le Média{% endblock %}

{% block body %}
<div class="admin-wrapper">
    <h1>Editer le Media</h1>
    <a href="{{ path('app_admin_media_index') }}">Retour à la liste</a>
    {{ include('admin_media/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    {{ include('admin_media/_delete_form.html.twig') }}
</div>
{% endblock %}

{% block javascripts %}
<script src="{{ asset('js/vignettes-admin.js') }}"></script>
<script>
window.addEventListener('load', (event) => {
  showImages('#media_oeuvres',"/images/oeuvres/");
});
</script>
{% endblock %}

templates/admin_media/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Les Médias{% endblock %}

{% block body %}
<div class="admin-wrapper">
    <h1>Les Médias</h1>
    <a href="{{ path('app_admin_media_new') }}">Nouveau Média</a>
    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Nom</th>
                {# <th>Description</th> #}
                <th>Actif</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for medium in media %}
            <tr>
                {# <td>{{ medium.id }}</td> #}
                <td>{{ medium.nom }}</td>
                {# <td>{{ medium.description }}</td> #}
                <td>{{ medium.actif ? 'Oui' : 'Non' }}</td>
                <td>
                    <a href="{{ path('app_admin_media_show', {'id': medium.id}) }}">Voir</a>
                    <a href="{{ path('app_admin_media_edit', {'id': medium.id}) }}">Editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Pas de média enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/admin_media/new.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Nouveau Média{% endblock %}

{% block body %}
<div class="admin-wrapper">
    <h1>Créer un nouveau Media</h1>
    <a href="{{ path('app_admin_media_index') }}">Retour à la liste</a>
    {{ include('admin_media/_form.html.twig') }}
</div>
{% endblock %}

templates/admin_media/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ medium.nom }}{% endblock %}

{% block body %}
<div class="admin-wrapper">
    <h1>{{ medium.nom }}</h1>
    <a href="{{ path('app_admin_media_index') }}">Retour à la liste</a>
    <a href="{{ path('app_admin_media_edit', {'id': medium.id}) }}">Editer</a>
    <table class="table">
        <tbody>
            {# <tr>
                <th>Id</th>
                <td>{{ medium.id }}</td>
            </tr> #}
            {# <tr>
                <th>Nom</th>
                <td>{{ medium.nom }}</td>
            </tr> #}
            <tr>
                <th>Description</th>
                <td>{{ medium.description }}</td>
            </tr>
            <tr>
                <th>Actif</th>
                <td>{{ medium.actif ? 'Oui' : 'Non' }}</td>
            </tr>
        </tbody>
    </table>

    {{ include('admin_media/_delete_form.html.twig') }}
</div>
{% endblock %}